(()=>{
const KEY='manthos_v34_path';
const paths={
 warrior:{name:'DE KRIJGER',sub:'CAPACITEIT',color:'#7A2634',icon:'⚔',tag:'Bouw capaciteit.',intro:'Vroeger kon je het je simpelweg niet veroorloven om fysiek totaal nutteloos te zijn. Tegenwoordig kan dat prima. Comfort is mooi, totdat je lichaam iets moet kunnen.',question:'Is jouw lichaam en hoofd nog in staat om te leveren als het nodig is?',anchor:'Een Krijger moet kunnen bewegen.',choices:['Krachttraining','Hardlopen','Wandelen','Vechtsport','Fietsen','Zwemmen','Anders'],suggest:['Slaap','Voeding','Conditie','Herstel','Mentale weerbaarheid'],pillar:'Fysiek'},
 guardian:{name:'DE HOEDER',sub:'VERANTWOORDELIJKHEID',color:'#F5C400',icon:'⬡',tag:'Breng rust.',intro:'Een huis, relatie, gezin, vriendschappen, geld en een agenda onderhouden zichzelf verdomd slecht. De Hoeder probeert niet alles te controleren. Hij zorgt vooral dat hij geen extra chaos toevoegt.',question:'Waar moet jij meer rust en verantwoordelijkheid brengen?',anchor:'Waar moet jij meer rust brengen?',choices:['In mijn hoofd','In mijn huis','In mijn relatie','In mijn gezin','In mijn financiën','In mijn agenda','Anders'],suggest:['Aanwezig zijn','Financiën','Relatie','Gezin','Orde'],pillar:'Relaties'},
 craftsman:{name:'DE VAKMAN',sub:'MEESTERSCHAP',color:'#244B6B',icon:'⚒',tag:'Bouw meesterschap.',intro:'Een vakman werd uiteindelijk op iets simpels beoordeeld: kon hij zijn vak of niet? Niet hoeveel hij erover gelezen had, maar wat hij daadwerkelijk kon maken, oplossen of uitvoeren.',question:'Wat moet jij leren om beter te worden in wat je doet?',anchor:'Leer wat nodig is. Niet alleen wat leuk is.',choices:['Vakinhoudelijke kennis','Praktische vaardigheid','Communicatie','Leiderschap','Technologie','Schrijven / spreken','Iets waar ik nu slecht in ben','Anders'],suggest:['Gericht leren','Oefenen','Feedback vragen','Deep work','Vakliteratuur'],pillar:'Ontwikkeling'}
};
let draft={path:null,anchor:null,freq:3,extras:[]};
const state=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const saveState=x=>localStorage.setItem(KEY,JSON.stringify(x));
function greekArt(k,color){const top=`<svg viewBox="0 0 420 190" xmlns="http://www.w3.org/2000/svg"><rect width="420" height="190" rx="18" fill="${color}"/><path d="M0 25h420M0 34h420M0 164h420" stroke="#101010" stroke-width="3" opacity=".8"/><path d="M12 16h396" stroke="#101010" stroke-width="2" stroke-dasharray="18 8" opacity=".8"/>`;if(k==='warrior')return top+`<circle cx="205" cy="63" r="20" fill="#101010"/><path d="M185 84c-30 14-45 41-44 77h83c2-36-11-62-39-77Z" fill="#101010"/><path d="M154 94 96 45M227 94l66-40" stroke="#101010" stroke-width="12" stroke-linecap="round"/><path d="M94 36v112M292 42v118" stroke="#101010" stroke-width="7"/><circle cx="294" cy="91" r="43" fill="none" stroke="#101010" stroke-width="10"/></svg>`;if(k==='guardian')return top+`<circle cx="160" cy="64" r="20" fill="#101010"/><path d="M137 84c-18 18-26 42-25 75h86c2-30-9-58-31-75Z" fill="#101010"/><circle cx="270" cy="79" r="17" fill="#101010"/><path d="M247 97c-19 16-27 36-24 62h73c0-28-10-49-30-62Z" fill="#101010"/><circle cx="221" cy="117" r="12" fill="#101010"/><path d="M208 128c-10 8-15 19-14 31h46c0-13-6-24-18-31Z" fill="#101010"/><path d="M34 159V96l42-32 42 32v63M320 159V88h60v71" fill="none" stroke="#101010" stroke-width="9"/></svg>`;return top+`<circle cx="196" cy="60" r="19" fill="#101010"/><path d="M175 80c-25 14-37 40-35 77h82c2-36-10-62-34-77Z" fill="#101010"/><path d="M150 103 89 137M219 102l70 29" stroke="#101010" stroke-width="12" stroke-linecap="round"/><path d="M68 139h290M83 139v25M342 139v25" stroke="#101010" stroke-width="9"/><rect x="275" y="112" width="48" height="21" fill="#101010"/><path d="m322 82 32 32M344 69l-38 49" stroke="#101010" stroke-width="7"/></svg>`}
function shell(html){let o=document.getElementById('v34Onboarding');if(!o){o=document.createElement('div');o.id='v34Onboarding';o.className='p34-overlay';document.body.appendChild(o)}o.innerHTML=`<main class="p34-shell">${html}</main>`;return o}
function choose(){draft={path:null,anchor:null,freq:3,extras:[]};const o=shell(`<div class="p34-kicker">MANTHOS HABITS</div><h1>Waar ligt het werk?</h1><p class="p34-lead">Je kunt aan tien dingen tegelijk werken. Meestal betekent dat vooral dat er nergens echt iets verandert. Kies voor de komende <b>30 dagen</b> één hoofdfocus.</p><div class="p34-cards">${Object.entries(paths).map(([k,p])=>`<button class="p34-card ${k}" data-path="${k}" style="--path:${p.color}"><span class="p34-art">${greekArt(k,p.color)}</span><b>${p.name}</b><em>${p.sub}</em><small>${p.tag}</small><i>BEKIJK DIT PAD →</i></button>`).join('')}</div><p class="p34-foot"><b>Je bent niet je pad.</b> Je kiest alleen waar de komende 30 dagen het meeste werk ligt.</p>`);o.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>detail(b.dataset.path))}
function detail(k){draft.path=k;const p=paths[k],o=shell(`<button class="p34-back">← Andere paden</button><section class="p34-detail" style="--path:${p.color}"><div class="p34-hero"><div class="p34-heroart">${greekArt(k,p.color)}</div><div><small>${p.sub}</small><h1>${p.name}</h1><b>${p.tag}</b></div></div><p>${p.intro}</p><blockquote>${p.question}</blockquote><div class="p34-anchor"><small>HET ANKER</small><h2>${p.anchor}</h2><div class="p34-options">${p.choices.map(x=>`<button data-anchor="${x}">${x}</button>`).join('')}</div></div><button class="p34-confirm" disabled>DIT PAD PAST NU BIJ MIJ</button></section>`);o.querySelector('.p34-back').onclick=choose;o.querySelectorAll('[data-anchor]').forEach(b=>b.onclick=()=>{let v=b.dataset.anchor;if(v==='Anders'){v=prompt('Wat wil jij als anker gebruiken?');if(!v||!v.trim())return;v=v.trim()}draft.anchor=v;o.querySelectorAll('[data-anchor]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');b.textContent=v;o.querySelector('.p34-confirm').disabled=false});o.querySelector('.p34-confirm').onclick=principle}
function principle(){const p=paths[draft.path],o=shell(`<section class="p34-principle" style="--path:${p.color}"><div class="p34-kicker">ÉÉN DING NOG</div><h1>Je bent niet je pad.</h1><p>Je bent geen Krijger, Hoeder of Vakman. Een capabele man heeft iets van alle drie nodig.</p><p>Je hebt alleen besloten dat bij <b>${p.name.replace('DE ','')}</b> de komende 30 dagen het meeste werk ligt.</p><blockquote>Focus op één.<br>Verwaarloos de rest niet.</blockquote><button class="p34-confirm">BEGREPEN — BOUW MIJN 30 DAGEN</button><button class="p34-textback">← Terug</button></section>`);o.querySelector('.p34-confirm').onclick=build;o.querySelector('.p34-textback').onclick=()=>detail(draft.path)}
function build(){const p=paths[draft.path],o=shell(`<section class="p34-build" style="--path:${p.color}"><button class="p34-back">← Terug</button><div class="p34-kicker">30 DAGEN ${p.name.replace('DE ','')}</div><h1>Maak het van jou.</h1><div class="p34-chosen"><span>${p.icon}</span><div><small>JOUW ANKER</small><b>${draft.anchor}</b></div></div><h3>Hoe vaak per week?</h3><div class="p34-freq">${[1,2,3,4,5,6,7].map(n=>`<button data-freq="${n}" class="${n===draft.freq?'selected':''}">${n}</button>`).join('')}</div><h3>Wat wil je eventueel nog meenemen?</h3><p class="p34-muted">Suggesties, geen verplichtingen. Tik aan wat bij jou past. Maximaal drie.</p><div class="p34-chips">${p.suggest.map(x=>`<button data-extra="${x}" class="${draft.extras.includes(x)?'selected':''}">+ ${x}</button>`).join('')}<button data-own>+ Eigen habit</button></div><button class="p34-confirm">START MIJN 30 DAGEN</button></section>`);o.querySelector('.p34-back').onclick=principle;o.querySelectorAll('[data-freq]').forEach(b=>b.onclick=()=>{draft.freq=+b.dataset.freq;o.querySelectorAll('[data-freq]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});o.querySelectorAll('[data-extra]').forEach(b=>b.onclick=()=>{const v=b.dataset.extra;if(draft.extras.includes(v))draft.extras=draft.extras.filter(x=>x!==v);else if(draft.extras.length<3)draft.extras.push(v);b.classList.toggle('selected',draft.extras.includes(v))});o.querySelector('[data-own]').onclick=()=>{const v=prompt('Welke gewoonte wil je meenemen?');if(v&&v.trim()&&draft.extras.length<3){draft.extras.push(v.trim());build()}};o.querySelector('.p34-confirm').onclick=finish}
function addHabits(p){if(typeof S==='undefined'||!S.habits||!S.habits[p.pillar])return;const add=(name,target)=>{if(!(S.habits[p.pillar]||[]).some(h=>h.name===name))S.habits[p.pillar].push({id:p.pillar+Date.now()+Math.random(),name,target})};add(draft.anchor,draft.freq);draft.extras.forEach(x=>add(x,1));if(typeof save==='function')save()}
function finish(){const now=new Date();const end=new Date(now);end.setDate(end.getDate()+30);const p=paths[draft.path];addHabits(p);saveState({path:draft.path,anchor:draft.anchor,frequency:draft.freq,extras:[...draft.extras],start:now.toISOString(),end:end.toISOString(),cycles:1,history:[]});apply();document.getElementById('v34Onboarding')?.remove();window.dispatchEvent(new CustomEvent('manthos:path-selected',{detail:state()}));if(typeof home==='function')home()}
function apply(){const s=state();if(!s)return false;const p=paths[s.path];if(p){document.documentElement.style.setProperty('--v34-accent',p.color);document.documentElement.style.setProperty('--gold',p.color);document.body.dataset.v34Path=s.path}return true}
window.MANTHOS_PATHS={paths,state,choose,apply,reset:()=>{localStorage.removeItem(KEY);choose()}};
function init(){if(!apply())setTimeout(choose,900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();