(()=>{
const COMMUNITY='https://manthos.mn.co';
const DASH_IMG='assets/navigation/Dashboard.png';
const NU_IMG='assets/navigation/Manthos-nu.png';
const baseReview=window.review;
const pathState=()=>window.MANTHOS_PATHS?.state?.();
const pathMeta=()=>{const s=pathState();return s?window.MANTHOS_PATHS.paths[s.path]:null};
const dayNo=()=>{const s=pathState();if(!s)return 1;return Math.min(30,Math.max(1,Math.floor((Date.now()-new Date(s.start).getTime())/86400000)+1))};
const ico={today:'<span class="navico navico-dot"></span>',progress:'<span class="navico navico-bars"><i></i><i></i><i></i></span>',path:'<svg class="navico navico-mountain" viewBox="0 0 28 20" aria-hidden="true"><path d="M2 18 10 7l4 5 3-4 9 10H2Z" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/><path d="m8.5 9 1.5-2 2 2" fill="none" stroke="currentColor" stroke-width="2"/></svg>'};
function openCommunity(){window.open(COMMUNITY,'_blank','noopener,noreferrer')}
function resetTestApp(){if(!confirm('Test-app volledig resetten? Alle lokaal opgeslagen Habits-data op dit apparaat wordt gewist.'))return;localStorage.clear();sessionStorage.clear();location.reload()}
function addReset(){if(document.getElementById('v34Reset'))return;const b=document.createElement('button');b.id='v34Reset';b.className='v34-devreset';b.textContent='RESET TEST';b.onclick=resetTestApp;document.body.appendChild(b)}
function buildHeader(){const top=document.querySelector('.top'),avatar=top?.querySelector('.avatar'),logo=document.querySelector('.word');if(!top||!avatar)return;if(logo){logo.innerHTML=`<img src="${DASH_IMG}" alt="Dashboard">`;logo.classList.add('v34-dashboard-logo');logo.title='Dashboard';logo.onclick=()=>home()}
let wrap=document.getElementById('v34TopActions');if(!wrap){wrap=document.createElement('div');wrap.id='v34TopActions';wrap.className='v34-topactions';top.insertBefore(wrap,avatar)}let b=document.getElementById('v34Agora');if(!b){b=document.createElement('button');b.id='v34Agora';b.className='v34-agora';b.onclick=openCommunity;wrap.appendChild(b)}b.innerHTML=`<img src="${NU_IMG}" alt="Manthos NU">`;b.title='Open Manthos NU';if(avatar.parentElement!==wrap)wrap.appendChild(avatar)}
function setActive(i){const n=[...document.querySelectorAll('.nav')];n.forEach((x,j)=>x.classList.toggle('v34-active',j===i))}
function updateBottom(){const n=[...document.querySelectorAll('.nav')];if(n.length<3)return;n[0].innerHTML=`${ico.today}<b>VANDAAG</b>`;n[0].onclick=()=>home();n[1].innerHTML=`${ico.progress}<b>VOORTGANG</b>`;n[1].onclick=()=>reflection();n[2].innerHTML=`${ico.path}<b>MIJN PAD</b>`;n[2].onclick=()=>myPath();n[0].parentElement?.classList.add('v34-navstrip')}
function reflection(){if(typeof baseReview==='function')baseReview();setTimeout(()=>setActive(1),0)}
function habitRows(pillar){if(typeof S==='undefined')return'';const today=typeof key==='function'?key():'';return (S.habits[pillar]||[]).map(h=>{const td=(S.logs[today]&&S.logs[today][h.id])||0;return`<div class="habit"><div><b>${typeof esc==='function'?esc(h.name):h.name}</b><small>${typeof count==='function'?count(h.id):0}/${h.target} deze week · vandaag ${td}</small></div><div class="counter"><button class="round" onclick="chg('${h.id}',-1)">−</button><span class="count">${td}</span><button class="round" onclick="chg('${h.id}',1)">+</button></div></div>`}).join('')}
function pathPrompt(){const s=pathState();if(!s)return'';const prompts={warrior:['IETS OM OP TE LETTEN','Beweeg je deze week omdat je het hebt afgesproken, of alleen wanneer het lekker uitkomt?'],guardian:['IETS OM OP TE LETTEN','Waar voeg jij zelf onnodige onrust toe aan huis, agenda of hoofd?'],craftsman:['IETS OM OP TE LETTEN','Leer je vooral wat je leuk vindt, of ook wat je echt nodig hebt om beter te worden?']};const x=prompts[s.path];return`<div class="v34-prompt"><span>${x[0]}</span><p>${x[1]}</p></div>`}
function homeV34(){const s=pathState(),p=pathMeta();if(!s||!p){window.MANTHOS_PATHS?.choose();return}if(typeof nav==='function')nav('');setActive(0);const t=typeof total==='function'?total():0;const main=document.getElementById('main');if(!main)return;main.innerHTML=`<section class="v34-homehero" style="--path:${p.color}"><div class="v34-route"><span>${p.icon}</span><div><small>DAG ${dayNo()} / 30</small><b>${p.name}</b><em>${p.sub}</em></div></div><div class="v34-homecopy"><h1>Vandaag.</h1><p>Je hoeft niet alles tegelijk beter te doen. Doe wat je met jezelf hebt afgesproken.</p></div><div class="v34-homegrid"><div><b>${t}%</b><span>deze week</span></div><div><b>${s.frequency}×</b><span>jouw concrete actie per week</span></div></div><div class="v34-anchorline"><small>JOUW ACTIE</small><b>${s.action||s.anchor}</b></div><button class="btn primary v34-mainbtn" onclick="tracker()">NAAR VANDAAG →</button></section>${pathPrompt()}<section class="v34-section"><div class="eyebrow">JOUW RICHTING</div><h2>De komende 30 dagen</h2><p class="muted">Focus op één. Verwaarloos de rest niet.</p><div class="goal"><div class="goalTop"><b>${p.name}</b><span>${p.icon}</span></div><p>${s.action||s.anchor} · ${s.frequency}× per week${s.extras?.length?' · '+s.extras.join(' · '):''}</p></div></section>`;if(typeof avatar==='function')avatar()}
function trackerV34(){const s=pathState(),p=pathMeta();if(!s||!p)return;typeof nav==='function'&&nav('track');setActive(0);const main=document.getElementById('main');const other=['Fysiek','Relaties','Ontwikkeling'].filter(x=>x!==p.pillar);main.innerHTML=`<div class="eyebrow">${p.name} · DAG ${dayNo()} / 30</div><h1>Wat doe je vandaag?</h1><div class="muted">Focus eerst op je gekozen pad. De rest is onderhoud.</div><div class="v34-focusbox" style="--path:${p.color}"><div><small>JOUW ACTIE</small><h2>${p.icon} ${p.sub}</h2><p>${s.action||s.anchor}</p></div><div class="pct">${typeof ps==='function'?ps(p.pillar):0}%</div></div>${habitRows(p.pillar)}<div style="display:flex;justify-content:space-between;align-items:center;margin:20px 0 8px"><h2>Focus habits</h2><button class="btn primary" onclick="curP='${p.pillar}';addHabit()">+ toevoegen</button></div><div class="v34-maint"><div class="eyebrow">ONDERHOUD</div><p class="muted">Alleen als jij dat nodig vindt. Je hoeft niet overal tegelijk vol op te gaan.</p>${other.map(x=>`<button class="v34-maintbtn" onclick="page('pillar','${x}')"><span>${x}</span><b>${typeof ps==='function'?ps(x):0}% →</b></button>`).join('')}</div>`;if(typeof avatar==='function')avatar()}
function browsePaths(){window.MANTHOS_PATHS?.browse?.()}
function changePath(){if(confirm('Weet je zeker dat je van pad wilt veranderen? Je huidige 30-dagenfocus wordt vervangen.'))window.MANTHOS_PATHS?.choose?.()}
function myPath(){const s=pathState(),p=pathMeta();if(!s||!p)return window.MANTHOS_PATHS.choose();typeof nav==='function'&&nav('info');setActive(2);const left=Math.max(0,30-dayNo());document.getElementById('main').innerHTML=`<div class="eyebrow">MIJN PAD</div><h1>${p.name}</h1><div class="v34-pathpanel" style="--path:${p.color}"><div class="v34-pathbig">${p.icon}</div><small>${p.sub}</small><h2>${p.tag}</h2><p>${s.action||s.anchor} · ${s.frequency}× per week</p><div class="bar"><i style="width:${Math.round(dayNo()/30*100)}%"></i></div><small>Dag ${dayNo()} van 30 · nog ${left} dagen</small></div><div class="v34-miniinfo"><button onclick="v34How()"><span>◎</span><b>Hoe werkt dit?</b><small>Vier simpele stappen</small></button><button class="v34-nu-card" onclick="window.open('${COMMUNITY}','_blank')"><img src="${NU_IMG}" alt="Manthos NU"><div><b>Manthos NU</b><small>Ga naar de Member Area</small></div></button></div><div class="v34-pathactions"><button onclick="browsePaths()">BEKIJK DE PADEN</button><button class="danger" onclick="changePath()">WISSEL VAN PAD</button></div>`;if(typeof avatar==='function')avatar()}
function how(){document.getElementById('main').innerHTML=`<button class="v34-backbtn" onclick="myPath()">TERUG NAAR MIJN PAD</button><div class="eyebrow">HOE WERKT HET?</div><h1>Hou het simpel.</h1><div class="v34-howgrid"><div><span>◎</span><b>RICHTING</b><p>Kies 30 dagen waar het werk ligt.</p></div><div><span>↻</span><b>HERHALING</b><p>Maak gedrag klein en concreet.</p></div><div><span>✓</span><b>DOEN</b><p>Registreer wat je echt uitvoert.</p></div><div><span class="v34-barsicon"><i></i><i></i><i></i></span><b>VOORTGANG</b><p>Kijk terug, zie je patroon en stuur bij.</p></div></div><section class="v34-why"><div class="eyebrow">WAAROM WERKT DIT?</div><h2>Gedrag groeit beter in een duidelijke omgeving.</h2><p>Een tracker maakt zichtbaar wat je daadwerkelijk doet. Maar alleen informatie verandert weinig. Richting, herhaling, terugkijken en mensen om je heen die dezelfde standaard serieus nemen maken gedrag sterker en beter vol te houden.</p><p>Daarom staat Manthos Habits niet los van Manthos. De tracker helpt je koers houden. De community voegt ritme, gesprekken en een sterke cultuur toe. Je hoeft geen lid te zijn om deze tracker te gebruiken, maar als je merkt dat je meer uit je omgeving wilt halen, kun je gratis aansluiten.</p><button class="v34-whybtn" onclick="window.open('${COMMUNITY}','_blank')"><img src="${NU_IMG}" alt="Manthos NU"><span>BEKIJK MANTHOS NU GRATIS</span></button></section><details class="v34-details"><summary>Gegevens & onderbouwing</summary><p>Je trackerdata staat lokaal op dit apparaat. Wis je browser- of appgegevens, dan kan die lokale data verloren gaan.</p></details>`}
function installOverrides(){window.home=homeV34;window.tracker=trackerV34;window.myPath=myPath;window.v34How=how;window.browsePaths=browsePaths;window.changePath=changePath;window.v34ResetTest=resetTestApp;buildHeader();addReset();updateBottom();document.getElementById('v34Trigger')?.remove();if(pathState())homeV34()}
window.addEventListener('manthos:path-selected',()=>setTimeout(installOverrides,0));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(installOverrides,50));else setTimeout(installOverrides,50);
})();