(()=>{
const COMMUNITY='https://manthos.mn.co';
const pathState=()=>window.MANTHOS_PATHS?.state?.();
const pathMeta=()=>{const s=pathState();return s?window.MANTHOS_PATHS.paths[s.path]:null};
const dayNo=()=>{const s=pathState();if(!s)return 1;return Math.min(30,Math.max(1,Math.floor((Date.now()-new Date(s.start).getTime())/86400000)+1))};
function openCommunity(){window.open(COMMUNITY,'_blank','noopener,noreferrer')}
function resetTestApp(){if(!confirm('Test-app volledig resetten? Alle lokaal opgeslagen Habits-data op dit apparaat wordt gewist.'))return;localStorage.clear();sessionStorage.clear();location.reload()}
function addReset(){if(document.getElementById('v34Reset'))return;const b=document.createElement('button');b.id='v34Reset';b.className='v34-devreset';b.textContent='RESET TEST';b.title='Alleen voor ontwikkeling: start als nieuwe gebruiker';b.onclick=resetTestApp;document.body.appendChild(b)}
function addAgora(){const top=document.querySelector('.top');const avatar=top?.querySelector('.avatar');if(!top||!avatar||document.getElementById('v34Agora'))return;const wrap=document.createElement('div');wrap.className='v34-topactions';const b=document.createElement('button');b.id='v34Agora';b.className='v34-agora';b.innerHTML='<span>⌂</span><small>AGORA</small>';b.title='Open Manthos Member Area';b.onclick=openCommunity;top.insertBefore(wrap,avatar);wrap.appendChild(b);wrap.appendChild(avatar)}
function updateBottom(){const n=[...document.querySelectorAll('.nav')];if(n.length<3)return;n[0].innerHTML='<span>●</span>VANDAAG';n[0].onclick=()=>home();n[1].innerHTML='<span>▦</span>REVIEW';n[1].onclick=()=>review();n[2].innerHTML='<span>◇</span>MIJN PAD';n[2].onclick=()=>myPath()}
function habitRows(pillar){if(typeof S==='undefined')return'';const today=typeof key==='function'?key():'';return (S.habits[pillar]||[]).map(h=>{const td=(S.logs[today]&&S.logs[today][h.id])||0;return`<div class="habit"><div><b>${typeof esc==='function'?esc(h.name):h.name}</b><small>${typeof count==='function'?count(h.id):0}/${h.target} deze week · vandaag ${td}</small></div><div class="counter"><button class="round" onclick="chg('${h.id}',-1)">−</button><span class="count">${td}</span><button class="round" onclick="chg('${h.id}',1)">+</button></div></div>`}).join('')}
function pathPrompt(){const s=pathState();if(!s)return'';const prompts={warrior:['IETS OM OP TE LETTEN','Beweeg je deze week omdat je het hebt afgesproken, of alleen wanneer het lekker uitkomt?'],guardian:['IETS OM OP TE LETTEN','Waar voeg jij zelf onnodige onrust toe aan huis, agenda of hoofd?'],craftsman:['IETS OM OP TE LETTEN','Leer je vooral wat je leuk vindt, of ook wat je echt nodig hebt om beter te worden?']};const x=prompts[s.path];return`<div class="v34-prompt"><span>${x[0]}</span><p>${x[1]}</p></div>`}
function homeV34(){const s=pathState(),p=pathMeta();if(!s||!p){window.MANTHOS_PATHS?.choose();return}if(typeof nav==='function')nav('');const t=typeof total==='function'?total():0;const main=document.getElementById('main');if(!main)return;main.innerHTML=`<section class="v34-homehero" style="--path:${p.color}"><div class="v34-route"><span>${p.icon}</span><div><small>DAG ${dayNo()} / 30</small><b>${p.name}</b><em>${p.sub}</em></div></div><div class="v34-homecopy"><h1>Vandaag.</h1><p>Je hoeft niet alles tegelijk beter te doen. Doe wat je met jezelf hebt afgesproken.</p></div><div class="v34-homegrid"><div><b>${t}%</b><span>deze week</span></div><div><b>${s.frequency}×</b><span>anker per week</span></div></div><div class="v34-anchorline"><small>JOUW ANKER</small><b>${s.anchor}</b></div><button class="btn primary v34-mainbtn" onclick="tracker()">NAAR VANDAAG →</button></section>${pathPrompt()}<section class="v34-section"><div class="eyebrow">JOUW RICHTING</div><h2>De komende 30 dagen</h2><p class="muted">Focus op één. Verwaarloos de rest niet.</p><div class="goal"><div class="goalTop"><b>${p.name}</b><span>${p.icon}</span></div><p>${s.anchor} · ${s.frequency}× per week${s.extras?.length?' · '+s.extras.join(' · '):''}</p></div></section>`;if(typeof avatar==='function')avatar()}
function trackerV34(){const s=pathState(),p=pathMeta();if(!s||!p)return;typeof nav==='function'&&nav('track');const main=document.getElementById('main');const other=['Fysiek','Relaties','Ontwikkeling'].filter(x=>x!==p.pillar);main.innerHTML=`<div class="eyebrow">${p.name} · DAG ${dayNo()} / 30</div><h1>Wat doe je vandaag?</h1><div class="muted">Focus eerst op je gekozen pad. De rest is onderhoud.</div><div class="v34-focusbox" style="--path:${p.color}"><div><small>FOCUS</small><h2>${p.icon} ${p.sub}</h2><p>${s.anchor}</p></div><div class="pct">${typeof ps==='function'?ps(p.pillar):0}%</div></div>${habitRows(p.pillar)}<div style="display:flex;justify-content:space-between;align-items:center;margin:20px 0 8px"><h2>Focus habits</h2><button class="btn primary" onclick="curP='${p.pillar}';addHabit()">+ toevoegen</button></div><div class="v34-maint"><div class="eyebrow">ONDERHOUD</div><p class="muted">Alleen als jij dat nodig vindt. Je hoeft niet overal tegelijk vol op te gaan.</p>${other.map(x=>`<button class="v34-maintbtn" onclick="page('pillar','${x}')"><span>${x}</span><b>${typeof ps==='function'?ps(x):0}% →</b></button>`).join('')}</div>`;if(typeof avatar==='function')avatar()}
function myPath(){const s=pathState(),p=pathMeta();if(!s||!p)return window.MANTHOS_PATHS.choose();typeof nav==='function'&&nav('info');const left=Math.max(0,30-dayNo());document.getElementById('main').innerHTML=`<div class="eyebrow">MIJN PAD</div><h1>${p.name}</h1><div class="v34-pathpanel" style="--path:${p.color}"><div class="v34-pathbig">${p.icon}</div><small>${p.sub}</small><h2>${p.tag}</h2><p>${s.anchor} · ${s.frequency}× per week</p><div class="bar"><i style="width:${Math.round(dayNo()/30*100)}%"></i></div><small>Dag ${dayNo()} van 30 · nog ${left} dagen</small></div><div class="v34-miniinfo"><button onclick="v34How()"><span>◎</span><b>Hoe werkt dit?</b><small>Vier simpele stappen</small></button><button onclick="window.open('${COMMUNITY}','_blank')"><span>⌂</span><b>Manthos Agora</b><small>Ga naar de Member Area</small></button></div><button class="btn secondary v34-switch" onclick="window.MANTHOS_PATHS.reset()">Bekijk / wissel van pad</button>`;if(typeof avatar==='function')avatar()}
function how(){document.getElementById('main').innerHTML=`<button class="back" onclick="myPath()">← Mijn pad</button><div class="eyebrow">HOE WERKT HET?</div><h1>Hou het simpel.</h1><div class="v34-howgrid"><div><span>🎯</span><b>RICHTING</b><p>Kies 30 dagen waar het werk ligt.</p></div><div><span>↻</span><b>HERHALING</b><p>Maak gedrag klein en concreet.</p></div><div><span>✓</span><b>DOEN</b><p>Registreer wat je echt uitvoert.</p></div><div><span>↺</span><b>REVIEW</b><p>Kijk terug en stuur bij.</p></div></div><details class="v34-details"><summary>Gegevens & onderbouwing</summary><p>Je trackerdata staat lokaal op dit apparaat. Wis je browser- of appgegevens, dan kan die lokale data verloren gaan.</p><p>De uitgebreide bronnen blijven beschikbaar in de bestaande onderbouwing.</p></details>`}
function installOverrides(){window.home=homeV34;window.tracker=trackerV34;window.myPath=myPath;window.v34How=how;window.v34ResetTest=resetTestApp;addAgora();addReset();updateBottom();document.getElementById('v34Trigger')?.remove();if(pathState())homeV34()}
window.addEventListener('manthos:path-selected',()=>setTimeout(installOverrides,0));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(installOverrides,50));else setTimeout(installOverrides,50);
})();